# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12MuX8wstiC6cjZMqI282TA3B_OUChl4K
"""

import requests
import pandas as pd
import numpy as np
from tqdm import tqdm
import time
import logging
from datetime import datetime, timedelta
import warnings
import concurrent.futures
from threading import Lock
import random

# Игнорируем предупреждения
warnings.filterwarnings('ignore', category=FutureWarning)

# Настройка логирования
logging.basicConfig(level=logging.WARNING)

# ID групп операторов связи для мониторинга с названиями
VK_GROUPS = {
    '-8458649': 'МТС',
    '-26514504': 'Билайн',
    '-18098621': 'Теле2',
    '-50353992': 'Йота',
    '-3785': 'Мегафон'
}

VK_TOKEN = '954e97ed954e97ed954e97ed2d967306909954e954e97edfc65b931ccd5ae0f3c2a7afe'

# MWS настройки
MWS_URL = "https://tables.mws.ru/fusion/v1/datasheets/dstRtSXBewJh8lLCNz/records"
MWS_HEADERS = {
    "Authorization": "Bearer uskSID2MFKEnL7AVNUdLrnn",
    "Content-Type": "application/json"
}
MWS_PARAMS = {
    "viewId": "viwYvxvon7TBU",
    "fieldKey": "name"
}

# Лимит постов на группу
MAX_POSTS_PER_GROUP = 8000

# Дата ограничения - 11 ноября 2025
CUTOFF_DATE = datetime(2025, 11, 11)

# Глобальные счетчики
success_count = 0
error_count = 0
counter_lock = Lock()

class VKDataCollector:
    def __init__(self, vk_token, api_version='5.199'):
        self.vk_token = vk_token
        self.api_version = api_version
        self.base_url = 'https://api.vk.com/method/'
        self.session = requests.Session()
        self.session.headers.update({
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        })

    def get_wall_posts(self, owner_id, offset=0, count=100, end_time=None):
        """Получение постов со стены до указанной даты"""
        time.sleep(0.1)

        method = 'wall.get'
        params = {
            'access_token': self.vk_token,
            'owner_id': owner_id,
            'v': self.api_version,
            'offset': offset,
            'count': count,
            'extended': 0
        }

        if end_time:
            params['end_time'] = int(end_time.timestamp())

        try:
            response = self.session.get(f"{self.base_url}{method}", params=params, timeout=10)
            response.raise_for_status()
            data = response.json()

            if 'error' in data:
                error_code = data['error'].get('error_code')
                if error_code in [6, 9, 29]:
                    time.sleep(2)
                return None

            return data

        except Exception:
            return None

    def calculate_er(self, likes, reposts, comments, views):
        if not views or views == 0:
            return 0
        return ((likes + reposts + comments) / views) * 100

    def categorize_efficiency(self, er):
        if er >= 8:
            return "Высокая"
        elif er >= 4:
            return "Средняя"
        elif er >= 2:
            return "Низкая"
        else:
            return "Очень низкая"

    def extract_post_data(self, post, group_name):
        try:
            post_id = post.get('id')
            owner_id = post.get('owner_id')
            date_timestamp = post.get('date')
            text = post.get('text', '')

            likes = post.get('likes', {}).get('count', 0)
            reposts = post.get('reposts', {}).get('count', 0)
            comments = post.get('comments', {}).get('count', 0)
            views = post.get('views', {}).get('count') if post.get('views') else 0

            title = ''
            for attachment in post.get('attachments', [])[:2]:
                attachment_type = attachment.get('type')
                if attachment_type in ['link', 'video', 'photo']:
                    attachment_data = attachment.get(attachment_type, {})
                    title = attachment_data.get('title', '')[:300]
                    break

            er = self.calculate_er(likes, reposts, comments, views)
            efficiency = self.categorize_efficiency(er)

            return {
                'id_group': group_name,
                'id_post': post_id,
                'date_time': date_timestamp,
                'title': title,
                'text': text[:1000],
                'views': views,
                'likes': likes,
                'reposts': reposts,
                'comments': comments,
                'ER': round(er, 2),
                'Efficiency': efficiency,
                'day_of_week': ["Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота", "Воскресенье"][datetime.fromtimestamp(date_timestamp).weekday()],
                'date': datetime.fromtimestamp(date_timestamp).strftime('%Y-%m-%d'),
                'time_period': self.get_time_period(date_timestamp),
                'len_text': len(text)
            }

        except Exception as e:
            print(f"❌ Ошибка извлечения данных поста: {e}")
            return None

    def get_time_period(self, timestamp):
        hour = datetime.fromtimestamp(timestamp).hour
        if 6 <= hour < 12:
            return "Утро"
        elif 12 <= hour < 18:
            return "День"
        elif 18 <= hour < 24:
            return "Вечер"
        else:
            return "Ночь"

def upload_batch_to_mws(posts_data):
    """Загрузка батча постов в MWS без проверки дубликатов"""
    global success_count, error_count

    if not posts_data:
        return 0

    print(f"📤 Загружаем {len(posts_data)} постов")

    records = []
    for post in posts_data:
        records.append({
            "post_id": str(post['id_post']),
            "title": str(post['title']),
            "text": str(post['text']),
            "attachment_description": "Отсутствует",
            "views": int(post['views']),
            "likes": int(post['likes']),
            "reposts": int(post['reposts']),
            "comments_count": int(post['comments']),
            "comments": "Нет комментариев",
            "post_date_time": int(post['date_time']) * 1000,
            "owner_id": str(post['id_group']),
            "ER": float(post['ER']),
            "Efficiency": str(post['Efficiency']),
            "day_of_week": str(post['day_of_week']),
            "post_date": int(post['date_time']) * 1000,
            "time_period": str(post['time_period']),
            "len_text": int(post['len_text'])
        })

    data = {
        "records": [{'fields': record} for record in records],
        "fieldKey": "name"
    }

    try:
        response = requests.post(
            MWS_URL,
            params=MWS_PARAMS,
            headers=MWS_HEADERS,
            json=data,
            timeout=15
        )

        if response.status_code in [200, 201]:
            with counter_lock:
                success_count += len(posts_data)
            print(f"✅ Успешно загружено {len(posts_data)} постов")
            return len(posts_data)
        else:
            print(f"❌ Ошибка батчевой загрузки: {response.status_code} - {response.text}")
            # Fallback на одиночную загрузку
            successful = 0
            for post in posts_data:
                if upload_single_post(post):
                    successful += 1
            return successful

    except Exception as e:
        print(f"❌ Ошибка батчевой загрузки: {e}")
        # Fallback на одиночную загрузку
        successful = 0
        for post in posts_data:
            if upload_single_post(post):
                successful += 1
        return successful

def upload_single_post(post_data):
    """Загрузка одного поста в MWS без проверки дубликатов"""
    global success_count, error_count

    post_id = str(post_data['id_post'])

    try:
        record = {
            "post_id": post_id,
            "title": str(post_data['title']),
            "text": str(post_data['text']),
            "attachment_description": "Отсутствует",
            "views": int(post_data['views']),
            "likes": int(post_data['likes']),
            "reposts": int(post_data['reposts']),
            "comments_count": int(post_data['comments']),
            "comments": "Нет комментариев",
            "post_date_time": int(post_data['date_time']) * 1000,
            "owner_id": str(post_data['id_group']),
            "ER": float(post_data['ER']),
            "Efficiency": str(post_data['Efficiency']),
            "day_of_week": str(post_data['day_of_week']),
            "post_date": int(post_data['date_time']) * 1000,
            "time_period": str(post_data['time_period']),
            "len_text": int(post_data['len_text'])
        }

        data = {
            "records": [{'fields': record}],
            "fieldKey": "name"
        }

        response = requests.post(
            MWS_URL,
            params=MWS_PARAMS,
            headers=MWS_HEADERS,
            json=data,
            timeout=10
        )

        if response.status_code in [200, 201]:
            with counter_lock:
                success_count += 1
            return True
        else:
            error_text = response.text.lower()
            # Игнорируем ошибки дубликатов
            if "duplicate" in error_text or "уже существует" in error_text:
                print(f"⚠️ Пост {post_id} уже существует (пропускаем)")
                with counter_lock:
                    success_count += 1  # Считаем как успешную обработку
                return True
            else:
                print(f"❌ Ошибка загрузки поста {post_id}: {response.status_code} - {response.text}")
                with counter_lock:
                    error_count += 1
                return False

    except Exception as e:
        print(f"❌ Ошибка соединения для поста {post_id}: {e}")
        with counter_lock:
            error_count += 1
        return False

def collect_posts_from_group(owner_id, group_name):
    """Сбор постов из группы до 11.11.2025 с лимитом 8000"""
    global success_count, error_count

    collector = VKDataCollector(VK_TOKEN)

    print(f"👥 Группа {group_name}: сбор постов до {CUTOFF_DATE}")

    # Получаем общее количество постов
    test_data = collector.get_wall_posts(owner_id, 0, 1, CUTOFF_DATE)
    if not test_data:
        print(f"❌ Не удалось получить данные для группы {group_name}")
        return 0

    total_posts = test_data['response']['count']
    print(f"📊 Всего постов в группе: {total_posts}")

    if total_posts == 0:
        print(f"📭 Постов не найдено")
        return 0

    # Ограничиваем лимитом
    posts_to_collect = min(total_posts, MAX_POSTS_PER_GROUP)
    print(f"🎯 Будет собрано: {posts_to_collect} постов")

    # Собираем и загружаем посты
    offset = 0
    processed_count = 0

    with tqdm(total=posts_to_collect, desc=f"Группа {group_name}") as pbar:
        while processed_count < posts_to_collect:
            remaining = posts_to_collect - processed_count
            count = min(100, remaining)

            wall_data = collector.get_wall_posts(owner_id, offset, count, CUTOFF_DATE)
            if not wall_data:
                break

            posts = wall_data['response']['items']
            if not posts:
                break

            batch_posts = []
            for post in posts:
                if processed_count >= posts_to_collect:
                    break

                post_data = collector.extract_post_data(post, group_name)
                if post_data:
                    batch_posts.append(post_data)
                processed_count += 1
                pbar.update(1)

            if batch_posts:
                upload_batch_to_mws(batch_posts)

            offset += 100
            time.sleep(0.3)

    print(f"✅ Группа {group_name}: обработано {processed_count} постов")
    return processed_count

def main_full_export():
    """Основная функция для полной выгрузки"""
    global success_count, error_count

    print("🚀 ЗАПУСК ПОЛНОЙ ВЫГРУЗКИ ДАННЫХ")
    print("🎯 Режим: сбор всех постов до 11.11.2025")
    print(f"📊 Лимит: {MAX_POSTS_PER_GROUP} постов на группу")
    print(f"📅 Ограничение по дате: до {CUTOFF_DATE}")
    print("🛡️  Защита от дубликатов: ОТКЛЮЧЕНА")
    print("🏷️  Владелец поста: название группы")
    print(f"📋 Целевая таблица: {MWS_URL}")
    print("=" * 60)

    start_time = time.time()

    # Сбрасываем счетчики
    success_count = 0
    error_count = 0

    total_processed = 0

    # Обрабатываем группы
    for i, (owner_id, group_name) in enumerate(VK_GROUPS.items()):
        print(f"\n{'='*50}")
        print(f"🔄 Группа {i+1}/{len(VK_GROUPS)}: {group_name} ({owner_id})")
        print(f"{'='*50}")

        processed = collect_posts_from_group(owner_id, group_name)
        total_processed += processed

        if i < len(VK_GROUPS) - 1:
            time.sleep(1)

    total_time = time.time() - start_time

    print(f"\n{'='*60}")
    print("📊 ФИНАЛЬНАЯ СТАТИСТИКА")
    print(f"{'='*60}")
    print(f"✅ Успешно загружено: {success_count}")
    print(f"❌ Ошибок: {error_count}")
    print(f"📄 Всего обработано: {total_processed}")
    print(f"⏱️ Время выполнения: {total_time:.1f} сек")
    print(f"📅 Ограничение по дате: до {CUTOFF_DATE}")

    if success_count > 0:
        print(f"\n🎉 ПОЛНАЯ ВЫГРУЗКА УСПЕШНО ЗАВЕРШЕНА!")
        print(f"💫 Добавлено {success_count} постов")
        print(f"🏷️  Владельцы постов: названия групп")
    else:
        print(f"\nℹ️ Постов не найдено")

if __name__ == "__main__":
    main_full_export()