# -*- coding: utf-8 -*-
"""автообнова

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hk_1HcQ4Z7yOjMQF-1f0gDhrqw4qS9RO
"""

import requests
import pandas as pd
import numpy as np
from tqdm import tqdm
import time
import logging
from datetime import datetime, timedelta
import warnings
import concurrent.futures
from threading import Lock
import random

# Игнорируем предупреждения
warnings.filterwarnings('ignore', category=FutureWarning)

# Настройка логирования
logging.basicConfig(level=logging.WARNING)

# Словарь групп операторов связи для мониторинга (ID -> название)
VK_GROUPS = {
    '-8458649': 'МТС',    # МТС
    '-26514504': 'Билайн', # Билайн
    '-18098621': 'Теле2',  # Теле2
    '-50353992': 'Йота',   # Йота
    '-3785': 'Мегафон'     # Мегафон
}

VK_TOKEN = '954e97ed954e97ed954e97ed2d967306909954e954e97edfc65b931ccd5ae0f3c2a7afe'

# MWS настройки для таблицы
MWS_URL = "https://tables.mws.ru/fusion/v1/datasheets/dstRtSXBewJh8lLCNz/records"
MWS_HEADERS = {
    "Authorization": "Bearer uskSID2MFKEnL7AVNUdLrnn",
    "Content-Type": "application/json"
}
MWS_PARAMS = {
    "viewId": "viwYvxvon7TBU",
    "fieldKey": "name"
}

# Лимит постов на группу
MAX_POSTS_PER_GROUP = 8000

# Специальная запись для хранения времени последнего обновления
LAST_UPDATE_RECORD_ID = "last_update_tracker"

# Глобальные счетчики
success_count = 0
error_count = 0
counter_lock = Lock()

class FastVKDataCollector:
    def __init__(self, vk_token, api_version='5.199'):
        self.vk_token = vk_token
        self.api_version = api_version
        self.base_url = 'https://api.vk.com/method/'
        self.session = requests.Session()
        self.session.headers.update({
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        })

    def get_wall_posts_fast(self, owner_id, offset=0, count=100):
        """Быстрое получение постов без ретраев"""
        time.sleep(0.05)  # Минимальная задержка

        method = 'wall.get'
        params = {
            'access_token': self.vk_token,
            'owner_id': owner_id,
            'v': self.api_version,
            'offset': offset,
            'count': count,
            'extended': 0
        }

        try:
            response = self.session.get(f"{self.base_url}{method}", params=params, timeout=5)
            response.raise_for_status()
            data = response.json()

            if 'error' in data:
                error_code = data['error'].get('error_code')
                if error_code in [6, 9, 29]:  # Rate limit ошибки
                    time.sleep(1)
                return None

            return data

        except Exception:
            return None

    def calculate_er(self, likes, reposts, comments, views):
        if not views or views == 0:
            return 0
        return ((likes + reposts + comments) / views) * 100

    def categorize_efficiency(self, er):
        if er >= 8:
            return "Высокая"
        elif er >= 4:
            return "Средняя"
        elif er >= 2:
            return "Низкая"
        else:
            return "Очень низкая"

    def extract_post_data_fast(self, post, group_name):
        try:
            post_id = post.get('id')
            owner_id = post.get('owner_id')
            date_timestamp = post.get('date')
            text = post.get('text', '')

            likes = post.get('likes', {}).get('count', 0)
            reposts = post.get('reposts', {}).get('count', 0)
            comments = post.get('comments', {}).get('count', 0)
            views = post.get('views', {}).get('count') if post.get('views') else 0

            # Быстрый поиск заголовка
            title = ''
            for attachment in post.get('attachments', [])[:1]:
                attachment_type = attachment.get('type')
                if attachment_type in ['link', 'video']:
                    attachment_data = attachment.get(attachment_type, {})
                    title = attachment_data.get('title', '')[:200]
                    break

            er = self.calculate_er(likes, reposts, comments, views)
            efficiency = self.categorize_efficiency(er)

            return {
                'id_group': owner_id,
                'group_name': group_name,
                'id_post': post_id,
                'date_time': date_timestamp,
                'title': title,
                'text': text[:500],
                'views': views,
                'likes': likes,
                'reposts': reposts,
                'comments_count': comments,
                'ER': round(er, 2),
                'Efficiency': efficiency,
                'day_of_week': ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"][datetime.fromtimestamp(date_timestamp).weekday()],
                'date': datetime.fromtimestamp(date_timestamp).strftime('%Y-%m-%d'),
                'time_period': self.get_time_period_fast(date_timestamp),
                'len_text': len(text)
            }

        except Exception:
            return None

    def get_time_period_fast(self, timestamp):
        hour = datetime.fromtimestamp(timestamp).hour
        if 6 <= hour < 12:
            return "Утро"
        elif 12 <= hour < 18:
            return "День"
        elif 18 <= hour < 24:
            return "Вечер"
        else:
            return "Ночь"

def get_last_update_date():
    """Получает дату последнего обновления из таблицы"""
    try:
        params = {
            **MWS_PARAMS,
            "recordIds": LAST_UPDATE_RECORD_ID
        }

        response = requests.get(
            MWS_URL,
            params=params,
            headers=MWS_HEADERS,
            timeout=10
        )

        if response.status_code == 200:
            data = response.json()
            if data and 'data' in data and data['data']:
                record = data['data'][0]
                post_date_time = record.get('fields', {}).get('post_date_time')
                if post_date_time:
                    # Конвертируем из миллисекунд в секунды
                    timestamp = post_date_time / 1000
                    last_update_date = datetime.fromtimestamp(timestamp)
                    print(f"📅 Найдена дата последнего обновления в таблице: {last_update_date}")
                    return last_update_date

        # Если запись не найдена, используем дату по умолчанию
        print("⚠️ Запись о последнем обновлении не найдена, используем дату по умолчанию: 11 октября 2025")
        return datetime(2025, 10, 11)

    except Exception as e:
        print(f"⚠️ Ошибка при получении даты обновления: {e}, используем дату по умолчанию: 11 октября 2025")
        return datetime(2025, 10, 11)

def upload_batch_to_mws(posts_data):
    global success_count, error_count

    if not posts_data:
        return 0

    records = []
    for post in posts_data:
        records.append({
            "post_id": str(post['id_post']),
            "title": str(post['title']),
            "text": str(post['text']),
            "attachment_description": "Отсутствует",
            "views": int(post['views']),
            "likes": int(post['likes']),
            "reposts": int(post['reposts']),
            "comments_count": int(post['comments_count']),
            "post_date_time": int(post['date_time']) * 1000,
            "owner_id": str(post['group_name']),  # Название группы вместо ID
            "ER": float(post['ER']),
            "Efficiency": str(post['Efficiency']),
            "day_of_week": str(post['day_of_week']),
            "post_date": int(post['date_time']) * 1000,
            "time_period": str(post['time_period']),
            "len_text": int(post['len_text'])
        })

    data = {
        "records": [{'fields': record} for record in records],
        "fieldKey": "name"
    }

    try:
        response = requests.post(
            MWS_URL,
            params=MWS_PARAMS,
            headers=MWS_HEADERS,
            json=data,
            timeout=10
        )

        if response.status_code in [200, 201]:
            with counter_lock:
                success_count += len(posts_data)
            return len(posts_data)
        else:
            # Если батч не прошел, пробуем по одному
            successful = 0
            for post in posts_data:
                if upload_single_post_fast(post):
                    successful += 1
            return successful

    except Exception:
        # Fallback на одиночную загрузку
        successful = 0
        for post in posts_data:
            if upload_single_post_fast(post):
                successful += 1
        return successful

def upload_single_post_fast(post_data):
    global success_count, error_count

    try:
        record = {
            "post_id": str(post_data['id_post']),
            "title": str(post_data['title']),
            "text": str(post_data['text']),
            "attachment_description": "Отсутствует",
            "views": int(post_data['views']),
            "likes": int(post_data['likes']),
            "reposts": int(post_data['reposts']),
            "comments_count": int(post_data['comments_count']),
            "post_date_time": int(post_data['date_time']) * 1000,
            "owner_id": str(post_data['group_name']),  # Название группы вместо ID
            "ER": float(post_data['ER']),
            "Efficiency": str(post_data['Efficiency']),
            "day_of_week": str(post_data['day_of_week']),
            "post_date": int(post_data['date_time']) * 1000,
            "time_period": str(post_data['time_period']),
            "len_text": int(post_data['len_text'])
        }

        data = {
            "records": [{'fields': record}],
            "fieldKey": "name"
        }

        response = requests.post(
            MWS_URL,
            params=MWS_PARAMS,
            headers=MWS_HEADERS,
            json=data,
            timeout=5
        )

        if response.status_code in [200, 201]:
            with counter_lock:
                success_count += 1
            return True
        else:
            error_text = response.text.lower()
            if "duplicate" in error_text or "уже существует" in error_text:
                with counter_lock:
                    success_count += 1
                return True
            return False

    except Exception:
        with counter_lock:
            error_count += 1
        return False

def find_start_offset(collector, owner_id, total_posts, cutoff_date):
    """Бинарный поиск для быстрого нахождения постов до cutoff даты"""
    print("🔍 Быстрый поиск стартовой позиции...")

    low = 0
    high = min(total_posts, 2000)  # Ограничиваем поиск первыми 2000 постами
    cutoff_timestamp = cutoff_date.timestamp()

    while low <= high:
        mid = (low + high) // 2
        print(f"   Проверка offset {mid}...")

        data = collector.get_wall_posts_fast(owner_id, mid, 1)
        if not data or not data['response']['items']:
            break

        post = data['response']['items'][0]
        post_timestamp = post.get('date', 0)

        if post_timestamp > cutoff_timestamp:
            low = mid + 1
        else:
            high = mid - 1

    # Начинаем с найденной позиции
    start_offset = max(0, low - 50)  # Немного отступаем назад для надежности
    print(f"Начинаем с отступа: {start_offset}")
    return start_offset

def collect_group_posts_optimized(owner_id, group_name, cutoff_date):
    global success_count, error_count

    collector = FastVKDataCollector(VK_TOKEN)

    print(f"\n📊 Обработка группы: {group_name} ({owner_id})")

    # Получаем общее количество
    test_data = collector.get_wall_posts_fast(owner_id, 0, 1)
    if not test_data:
        print(f"❌ Не удалось получить данные для группы {group_name}")
        return 0

    total_posts = test_data['response']['count']
    print(f"📈 Всего постов: {total_posts}")

    if total_posts == 0:
        return 0

    # Определяем стартовую позицию
    start_offset = find_start_offset(collector, owner_id, total_posts, cutoff_date)

    collected = 0
    offset = start_offset
    batch_size = 100
    cutoff_timestamp = cutoff_date.timestamp()

    with tqdm(total=MAX_POSTS_PER_GROUP, desc=f"Группа {group_name}") as pbar:
        while collected < MAX_POSTS_PER_GROUP:
            # батч
            data = collector.get_wall_posts_fast(owner_id, offset, batch_size)
            if not data:
                break

            posts = data['response'].get('items', [])
            if not posts:
                break

            # Фильтруем и обрабатываем посты
            valid_posts = []
            for post in posts:
                if collected >= MAX_POSTS_PER_GROUP:
                    break

                post_timestamp = post.get('date', 0)
                if post_timestamp <= cutoff_timestamp:
                    post_data = collector.extract_post_data_fast(post, group_name)
                    if post_data:
                        valid_posts.append(post_data)
                        collected += 1
                        pbar.update(1)
                else:
                    # Пропускаем новые посты
                    collected += 1
                    pbar.update(1)

            # Загружаем валидные посты батчем
            if valid_posts:
                upload_batch_to_mws(valid_posts)

            offset += batch_size

            # Быстрая проверка: если все посты в батче новые, ускоряемся
            if len(valid_posts) == 0 and len(posts) > 0:
                # Увеличиваем шаг для пропуска новых постов
                skip_ahead = min(500, MAX_POSTS_PER_GROUP - collected)
                if skip_ahead > 100:
                    offset += skip_ahead - batch_size
                    pbar.update(skip_ahead)
                    collected += skip_ahead
                    print(f"⚡ Пропускаем {skip_ahead} новых постов")

    print(f"✅ Группа {group_name}: обработано {collected} постов")
    return collected

def main():
    """Основная функция для сбора данных"""
    global success_count, error_count

    print("🚀 ЗАПУСК СБОРА ДАННЫХ ИЗ VK")

    # Получаем дату последнего обновления из таблицы
    CUTOFF_DATE = get_last_update_date()

    print(f"📅 Сбор постов до: {CUTOFF_DATE}")
    print(f"🎯 Лимит: {MAX_POSTS_PER_GROUP} постов на группу")
    print(f"📊 Группы для обработки: {len(VK_GROUPS)}")
    for group_id, group_name in VK_GROUPS.items():
        print(f"   - {group_name} ({group_id})")
    print("=" * 60)

    start_time = time.time()
    total_processed = 0

    # Обрабатываем группы с максимальной скоростью
    for i, (group_id, group_name) in enumerate(VK_GROUPS.items()):
        print(f"\n{'='*50}")
        print(f"🔄 Группа {i+1}/{len(VK_GROUPS)}: {group_name}")
        print(f"{'='*50}")

        processed = collect_group_posts_optimized(group_id, group_name, CUTOFF_DATE)
        total_processed += processed

        # Минимальная пауза между группами
        if i < len(VK_GROUPS) - 1:
            time.sleep(0.5)

    total_time = time.time() - start_time

    print(f"\n{'='*60}")
    print("🎉 ФИНАЛЬНАЯ СТАТИСТИКА СБОРА ДАННЫХ")
    print(f"{'='*60}")
    print(f"✅ Успешно загружено: {success_count}")
    print(f"❌ Ошибок: {error_count}")
    print(f"📊 Всего обработано: {total_processed}")
    print(f"⏱️ Время выполнения: {total_time:.1f} сек")

    if total_processed > 0:
        speed = total_processed / total_time
        print(f"⚡ Скорость: {speed:.1f} постов/сек")
        print(f"📈 Эффективность: {speed * 60:.1f} постов/мин")

if __name__ == "__main__":
    main()