# -*- coding: utf-8 -*-
"""автообнова

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hk_1HcQ4Z7yOjMQF-1f0gDhrqw4qS9RO
"""

import requests
import pandas as pd
import numpy as np
from tqdm import tqdm
import time
import logging
from datetime import datetime, timedelta
import warnings
import concurrent.futures
from threading import Lock
import random

# Игнорируем предупреждения
warnings.filterwarnings('ignore', category=FutureWarning)

# Настройка логирования
logging.basicConfig(level=logging.WARNING)

# ID групп операторов связи для мониторинга
VK_GROUPS = [
    '-8458649',   # МТС
    '-26514504',  # Билайн
    '-18098621',  # Теле2
    '-50353992',  # Йота
    '-3785'       # Мегафон
]

VK_TOKEN = '954e97ed954e97ed954e97ed2d967306909954e954e97edfc65b931ccd5ae0f3c2a7afe'

# MWS настройки
MWS_URL = "https://tables.mws.ru/fusion/v1/datasheets/dstCNkL7G9iYsD0LY9/records"
MWS_HEADERS = {
    "Authorization": "Bearer uskSID2MFKEnL7AVNUdLrnn",
    "Content-Type": "application/json"
}
MWS_PARAMS = {
    "viewId": "viwYvxvon7TBU",
    "fieldKey": "name"
}

# Лимит постов на группу
MAX_POSTS_PER_GROUP = 8000

# Специальная запись для хранения времени последнего обновления
LAST_UPDATE_RECORD_ID = "last_update_tracker"

# Глобальные счетчики
success_count = 0
error_count = 0
counter_lock = Lock()

class VKDataCollector:
    def __init__(self, vk_token, api_version='5.199'):
        self.vk_token = vk_token
        self.api_version = api_version
        self.base_url = 'https://api.vk.com/method/'
        self.session = requests.Session()
        self.session.headers.update({
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        })

    def get_wall_posts(self, owner_id, offset=0, count=100, start_time=None):
        """Получение постов со стены"""
        time.sleep(0.1)

        method = 'wall.get'
        params = {
            'access_token': self.vk_token,
            'owner_id': owner_id,
            'v': self.api_version,
            'offset': offset,
            'count': count,
            'extended': 0
        }

        if start_time:
            params['start_time'] = int(start_time.timestamp())

        try:
            response = self.session.get(f"{self.base_url}{method}", params=params, timeout=10)
            response.raise_for_status()
            data = response.json()

            if 'error' in data:
                error_code = data['error'].get('error_code')
                if error_code in [6, 9, 29]:
                    time.sleep(2)
                return None

            return data

        except Exception:
            return None

    def calculate_er(self, likes, reposts, comments, views):
        if not views or views == 0:
            return 0
        return ((likes + reposts + comments) / views) * 100

    def categorize_efficiency(self, er):
        if er >= 8:
            return "Высокая"
        elif er >= 4:
            return "Средняя"
        elif er >= 2:
            return "Низкая"
        else:
            return "Очень низкая"

    def extract_post_data(self, post):
        try:
            post_id = post.get('id')
            owner_id = post.get('owner_id')
            date_timestamp = post.get('date')
            text = post.get('text', '')

            likes = post.get('likes', {}).get('count', 0)
            reposts = post.get('reposts', {}).get('count', 0)
            comments = post.get('comments', {}).get('count', 0)
            views = post.get('views', {}).get('count') if post.get('views') else 0

            title = ''
            for attachment in post.get('attachments', [])[:2]:
                attachment_type = attachment.get('type')
                if attachment_type in ['link', 'video', 'photo']:
                    attachment_data = attachment.get(attachment_type, {})
                    title = attachment_data.get('title', '')[:300]
                    break

            er = self.calculate_er(likes, reposts, comments, views)
            efficiency = self.categorize_efficiency(er)

            return {
                'id_group': owner_id,
                'id_post': post_id,
                'date_time': date_timestamp,
                'title': title,
                'text': text[:1000],
                'views': views,
                'likes': likes,
                'reposts': reposts,
                'comments': comments,
                'ER': round(er, 2),
                'Efficiency': efficiency,
                'day_of_week': ["Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота", "Воскресенье"][datetime.fromtimestamp(date_timestamp).weekday()],
                'date': datetime.fromtimestamp(date_timestamp).strftime('%Y-%m-%d'),
                'time_period': self.get_time_period(date_timestamp),
                'len_text': len(text)
            }

        except Exception as e:
            print(f"❌ Ошибка извлечения данных поста: {e}")
            return None

    def get_time_period(self, timestamp):
        hour = datetime.fromtimestamp(timestamp).hour
        if 6 <= hour < 12:
            return "Утро"
        elif 12 <= hour < 18:
            return "День"
        elif 18 <= hour < 24:
            return "Вечер"
        else:
            return "Ночь"

def get_last_update_time():
    try:
        params = {
            **MWS_PARAMS,
            "pageSize": 1,
            "filter": f'{{"operator":"and","conditions":[{{"field":"post_id","operator":"is","value":"{LAST_UPDATE_RECORD_ID}"}}]}}'
        }

        response = requests.get(
            MWS_URL,
            params=params,
            headers=MWS_HEADERS,
            timeout=10
        )

        if response.status_code == 200:
            data = response.json()
            records = data.get('data', {}).get('records', [])
            if records:
                last_update_timestamp = records[0]['fields'].get('post_date_time', 0) // 1000
                last_update_time = datetime.fromtimestamp(last_update_timestamp)
                print(f"📅 Найдено время последнего обновления: {last_update_time}")
                return last_update_time

        # Если записи нет, возвращаем очень старое время
        very_old_time = datetime.fromtimestamp(0)
        print(f"🆕 Запись времени обновления не найдена, начинаем с начала")
        return very_old_time

    except Exception as e:
        print(f"Ошибка при получении времени обновления: {e}")
        very_old_time = datetime.fromtimestamp(0)
        return very_old_time

def update_last_update_time():
    current_time = datetime.now()

    record_data = {
        "records": [{
            "fields": {
                "post_id": LAST_UPDATE_RECORD_ID,
                "title": "LAST_UPDATE_TRACKER",
                "text": f"Последнее обновление: {current_time}",
                "attachment_description": "Системная запись",
                "views": 0,
                "likes": 0,
                "reposts": 0,
                "comments_count": 0,
                "comments": "Системная запись для отслеживания времени обновления",
                "post_date_time": int(current_time.timestamp()) * 1000,
                "owner_id": "system",
                "ER": 0,
                "Efficiency": "Системная",
                "day_of_week": "Системная",
                "post_date": int(current_time.timestamp()) * 1000,
                "time_period": "Системное",
                "len_text": 0
            }
        }],
        "fieldKey": "name"
    }

    try:
        params = {
            **MWS_PARAMS,
            "recordIds": LAST_UPDATE_RECORD_ID
        }

        response = requests.put(
            MWS_URL,
            params=params,
            headers=MWS_HEADERS,
            json=record_data,
            timeout=10
        )

        if response.status_code not in [200, 201]:
            response = requests.post(
                MWS_URL,
                params=MWS_PARAMS,
                headers=MWS_HEADERS,
                json=record_data,
                timeout=10
            )

        if response.status_code in [200, 201]:
            print(f"✅ Время обновления установлено на: {current_time}")
            return True
        else:
            print(f"❌ Ошибка записи времени обновления: {response.status_code}")
            return False

    except Exception as e:
        print(f"❌ Ошибка при обновлении времени: {e}")
        return False

def upload_batch_to_mws(posts_data):
    """Загрузка батча постов в MWS"""
    global success_count, error_count

    if not posts_data:
        return 0

    records = []
    for post in posts_data:
        records.append({
            "post_id": str(post['id_post']),
            "title": str(post['title']),
            "text": str(post['text']),
            "attachment_description": "Отсутствует",
            "views": int(post['views']),
            "likes": int(post['likes']),
            "reposts": int(post['reposts']),
            "comments_count": int(post['comments']),
            "comments": "Нет комментариев",
            "post_date_time": int(post['date_time']) * 1000,
            "owner_id": str(post['id_group']),
            "ER": float(post['ER']),
            "Efficiency": str(post['Efficiency']),
            "day_of_week": str(post['day_of_week']),
            "post_date": int(post['date_time']) * 1000,
            "time_period": str(post['time_period']),
            "len_text": int(post['len_text'])
        })

    data = {
        "records": [{'fields': record} for record in records],
        "fieldKey": "name"
    }

    try:
        response = requests.post(
            MWS_URL,
            params=MWS_PARAMS,
            headers=MWS_HEADERS,
            json=data,
            timeout=15
        )

        if response.status_code in [200, 201]:
            with counter_lock:
                success_count += len(posts_data)
            return len(posts_data)
        else:
            # Fallback на одиночную загрузку
            successful = 0
            for post in posts_data:
                if upload_single_post(post):
                    successful += 1
            return successful

    except Exception:
        successful = 0
        for post in posts_data:
            if upload_single_post(post):
                successful += 1
        return successful

def upload_single_post(post_data):
    """Загрузка одного поста в MWS"""
    global success_count, error_count

    try:
        record = {
            "post_id": str(post_data['id_post']),
            "title": str(post_data['title']),
            "text": str(post_data['text']),
            "attachment_description": "Отсутствует",
            "views": int(post_data['views']),
            "likes": int(post_data['likes']),
            "reposts": int(post_data['reposts']),
            "comments_count": int(post_data['comments']),
            "comments": "Нет комментариев",
            "post_date_time": int(post_data['date_time']) * 1000,
            "owner_id": str(post_data['id_group']),
            "ER": float(post_data['ER']),
            "Efficiency": str(post_data['Efficiency']),
            "day_of_week": str(post_data['day_of_week']),
            "post_date": int(post_data['date_time']) * 1000,
            "time_period": str(post_data['time_period']),
            "len_text": int(post_data['len_text'])
        }

        data = {
            "records": [{'fields': record}],
            "fieldKey": "name"
        }

        response = requests.post(
            MWS_URL,
            params=MWS_PARAMS,
            headers=MWS_HEADERS,
            json=data,
            timeout=10
        )

        if response.status_code in [200, 201]:
            with counter_lock:
                success_count += 1
            return True
        else:
            error_text = response.text.lower()
            if "duplicate" in error_text or "уже существует" in error_text:
                with counter_lock:
                    success_count += 1
                return True
            return False

    except Exception:
        with counter_lock:
            error_count += 1
        return False

def collect_new_posts_from_group(owner_id, last_update_time):
    """Сбор новых постов из группы после последнего обновления"""
    global success_count, error_count

    collector = VKDataCollector(VK_TOKEN)

    print(f"Группа {owner_id}: поиск постов после {last_update_time}")

    # Считаем общее количество новых постов для прогресс-бара
    total_new_posts = 0
    offset = 0
    has_more_posts = True

    while has_more_posts and total_new_posts < MAX_POSTS_PER_GROUP:
        wall_data = collector.get_wall_posts(owner_id, offset, 100, last_update_time)
        if not wall_data:
            break

        posts = wall_data['response']['items']
        if not posts:
            break

        for post in posts:
            post_timestamp = post.get('date', 0)
            post_time = datetime.fromtimestamp(post_timestamp)
            if post_time > last_update_time and total_new_posts < MAX_POSTS_PER_GROUP:
                total_new_posts += 1
            else:
                has_more_posts = False
                break

        if has_more_posts:
            offset += 100

    if total_new_posts == 0:
        print(f"Новых постов не найдено")
        return 0

    limited_new_posts = min(total_new_posts, MAX_POSTS_PER_GROUP)
    print(f"   Найдено {total_new_posts} новых постов")
    print(f"   Будет обработано: {limited_new_posts} постов")

    # Собираем и загружаем посты
    offset = 0
    processed_count = 0
    has_more_posts = True

    with tqdm(total=limited_new_posts, desc=f"Группа {owner_id}") as pbar:
        while has_more_posts and processed_count < limited_new_posts:
            wall_data = collector.get_wall_posts(owner_id, offset, 100, last_update_time)
            if not wall_data:
                break

            posts = wall_data['response']['items']
            if not posts:
                break

            batch_posts = []
            for post in posts:
                post_timestamp = post.get('date', 0)
                post_time = datetime.fromtimestamp(post_timestamp)
                if post_time > last_update_time and processed_count < limited_new_posts:
                    post_data = collector.extract_post_data(post)
                    if post_data:
                        batch_posts.append(post_data)
                    processed_count += 1
                    pbar.update(1)
                else:
                    has_more_posts = False
                    break

            if batch_posts:
                upload_batch_to_mws(batch_posts)

            offset += 100
            time.sleep(0.3)

    print(f"✅ Группа {owner_id}: обработано {processed_count} новых постов")
    return processed_count

def main_incremental():
    """Основная функция для инкрементального обновления"""
    global success_count, error_count

    print("ЗАПУСК ИНКРЕМЕНТАЛЬНОГО ОБНОВЛЕНИЯ")
    print("Режим: сбор только новых постов")
    print(f"Лимит: {MAX_POSTS_PER_GROUP} постов на группу")
    print("=" * 60)

    # Получаем время последнего обновления
    last_update_time = get_last_update_time()

    start_time = time.time()

    # Сбрасываем счетчики
    success_count = 0
    error_count = 0

    total_processed = 0

    # Обрабатываем группы
    for i, group_id in enumerate(VK_GROUPS):
        print(f"\n{'='*50}")
        print(f"Группа {i+1}/{len(VK_GROUPS)}: {group_id}")
        print(f"{'='*50}")

        processed = collect_new_posts_from_group(group_id, last_update_time)
        total_processed += processed

        if i < len(VK_GROUPS) - 1:
            time.sleep(1)

    # Обновляем время последнего обновления только если были новые посты
    if success_count > 0:
        print(f"\nОбновляем дату последнего обновления...")
        update_last_update_time()

    total_time = time.time() - start_time

    print(f"\n{'='*60}")
    print("ФИНАЛЬНАЯ СТАТИСТИКА")
    print(f"{'='*60}")
    print(f"✅ Успешно загружено: {success_count}")
    print(f"❌ Ошибок: {error_count}")
    print(f"Всего обработано: {total_processed}")
    print(f"Время выполнения: {total_time:.1f} сек")

    if success_count > 0:
        print(f"\nИНКРЕМЕНТАЛЬНОЕ ОБНОВЛЕНИЕ УСПЕШНО ЗАВЕРШЕНО!")
        print(f"Добавлено {success_count} новых постов")
    else:
        print(f"\nℹНовых постов не найдено")

if __name__ == "__main__":
    main_incremental()